commun:
    resource: "@CommunBundle/Controller"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/users/login