services:
    ws.tz_msg:
        class: Bundle\CommunBundle\Service\PreFormatMsg
        public: true
        arguments: ["@service_container"]
#    commun.example:
#        class: Bundle\CommunBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
