services:
    ws.tz_msg:
        class: Bundle\CommunBundle\Service\PreFormatMsg
        public: true
        arguments: ["@service_container"]
    sekoliko_api.authentication_success_listener:
        class: Bundle\CommunBundle\EventListener\AuthentificationEventListener
        arguments:  ["@service_container"]
        tags:
           - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    sekoliko_api.authentication_failure_listener:
        class: Bundle\CommunBundle\EventListener\AuthentificationEventListener
        arguments:  ["@service_container"]
        tags:
        - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
#    commun.example:
#        class: Bundle\CommunBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
