services:
  tz.responses:
      class: Bundle\AdminBundle\Service\FosRestResponse
      public: true
      arguments: ["@ws.tz_msg"]

#    admin.example:
#        class: Bundle\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
